### ISSUE TITLE
Division of UDA in the dataset？

### ISSUE THREAD

**Issue by lzylzylzy123456** [lxycopper/PLU#1]
Great job, but about t1_ uda、t2_ uda、t3_ uda、t4_ uda,how did you divide it? I didn't find it in/PLU/datasets/OWOD_ Imagesets/

**Comment by yellowflying2** [comment]
请问解决了吗

**Comment by yellowflying2** [comment]
> Great job, but about t1_ uda、t2_ uda、t3_ uda、t4_ uda,how did you divide it? I didn't find it in/PLU/datasets/OWOD_ Imagesets/
请问解决了吗

**Comment by yellowflying2** [comment]
> Great job, but about t1_ uda、t2_ uda、t3_ uda、t4_ uda,how did you divide it? I didn't find it in/PLU/datasets/OWOD_ Imagesets/

请问解决了吗

**Comment by lxycopper** [comment]
Thanks for your questions and interest in my work. I have uploaded the required 'uda' files.

However, I have moved from this research area due to the impact of foundation models, and I am not sure whether this area is still worth falling in. Therefore, I may not be able to respond to issues or provide updates regularly, sorry for any inconvenience and latency.
